apiVersion: v1
kind: Service
metadata:
  name: report-ai-frontend
  namespace: report-ai
  labels:
    app: report-ai
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: report-ai
    component: frontend
